version: '3'
services:
  frontend:
    build: ./frontend
    image: krippix/gustelcard-fe
    container_name: gustelcard-fe
    ports:
      - "80:80"
    volumes:
      - ./frontend/cardgame:/usr/share/nginx/html/:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf